### ISSUE TITLE
Unable to resolve service "Application" to a factory

### ISSUE THREAD

**Issue by lowtower** [froschdesign/zend-expressive-navigation#4]
Hello @froschdesign,

I followed the quick-start from #2 and I get the following error:
```php
Unable to resolve service "Application" to a factory;
are you certain you provided it during configuration?
```
In `Zend\Navigation\Service\AbstractNavigationFactory` the `preparePages()` method tries to fetch the `Application` from the container.
```php
$application = $container->get('Application');
```

I have a `zend-expressive-skeleton` installation, so it should be there, shouldn't it?

Cheers,
LT.

**Comment by froschdesign** [comment]
@lowtower 
Please follow _my_ quick-start, because the config-provider from zend-navigation is not needed and wrong here!

https://github.com/froschdesign/zend-expressive-navigation/issues/2#issuecomment-414084853

**Comment by lowtower** [comment]
Ah,

okay, thanks a lot!

I followed _Your_ quick-start.
My problem was, that when `zend-component-installer` asks to inject the `ConfigProvider` I answered Yes for **all**, which includes `zend-navigation` also.
Should be mentioned in the quick-start not to do so!

Cheers,
LT.

**Comment by froschdesign** [comment]
@lowtower 
Thanks for feedback! 👍

**Comment by froschdesign** [comment]
> My problem was, that when zend-component-installer asks to inject the ConfigProvider I answered Yes for all, which includes zend-navigation also.

Btw. this is an important point. I think we can eliminate this problem with the package `zend-mvc-navigation`.
