### ISSUE TITLE
Usage with swoole - ExpressivePage should be stateless

### ISSUE THREAD

**Issue by nuxwin** [froschdesign/zend-expressive-navigation#6]
@froschdesign 

Good morning,

I'm switching to **swoole**. When using swoole, **[services must be stateless](https://docs.zendframework.com/zend-expressive-swoole/v1/considerations/#stateless-services)**.

This isn't the case of your **ExpressivePage** implementation  which is bound to the **navigation** service. While I can understand that the navigation service must be created only once, including page containers, the pages for which state is derivated from the current request shouldn't keep their state throughout subsequent requests. Basically put, state of pages should be recalculated on each requests.

Keeping the state of the pages with swoole produce wrong behavior (pages with unexpected active state). One way to workaround the  issue is to reset the **active** state when the **RouteResult** object is set, that is:

```php
    /**
     * @param RouteResult $routeResult
     */
    public function setRouteResult(RouteResult $routeResult) : void
    {
        $this->active = false; // Make sure that active state will be based on current request
        $this->routeResult = $routeResult;
    }
```
instead of
```php
    /**
     * @param RouteResult $routeResult
     */
    public function setRouteResult(RouteResult $routeResult) : void
    {
        $this->routeResult = $routeResult;
    }
```
I'm pretty sure that there are other issues like this with current implementation (such as the **hrefCache** property) but solving this one would be a good starting point.

Thank you.

**Comment by nuxwin** [comment]
@froschdesign My solution above is bad in regard of usage in async context... We should think about a contextual state...

**Comment by froschdesign** [comment]
The support of Swoole is not one of the current goals. The current development includes only the support of zend-expressive itself. The integration of Swoole can be added later, after the transfer to the zendframework organisation.
